//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.OutputHandler
{
	using Definitions;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OutputHandler : IOutputHandler
    {
		public virtual string[] buffer
		{
			get;
			set;
		}

		public virtual IOutputComposer OutputComposer
		{
			get;
			set;
		}

		public virtual ICommandComposer CommandComposer
		{
			get;
			set;
		}

		public virtual string getBufferedOutput()
		{
			throw new System.NotImplementedException();
		}

		public virtual void addOutputCommand(ICommand command)
		{
			throw new System.NotImplementedException();
		}

	}
}

