//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.OutputHandler
{
	using Definitions;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OutputHandler : IOutputHandler
    {
		public virtual List<string> buffer
		{
			get;
			set;
		}

		public virtual IOutputComposer outputComposer
		{
			get;
			set;
		}

		public virtual ICommandComposer commandComposer
		{
			get;
			set;
		}

        public OutputHandler(IOutputComposer outputComposer_, ICommandComposer commandComposer_)
        {
            outputComposer = outputComposer_;
            commandComposer = commandComposer_;
            buffer = new List<string>();
        }

        public virtual string getBufferedOutput()
		{
            string output = outputComposer.compose(buffer);
            buffer.Clear();
            return output;
        }

		public virtual void addOutputCommand(ICommand command)
		{
			throw new System.NotImplementedException();
		}

	}
}

