//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Listener
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Client
	{
		public virtual string name
		{
			get;
			set;
		}

		public virtual string ip
		{
			get;
			set;
		}

		public virtual boolean allowed
		{
			get;
			set;
		}

	}
}

