//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Listener
{
	using Definitions;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Listener
	{
		public virtual IEnumerable<Session> runningSessions
		{
			get;
			set;
		}

		public virtual Client clients
		{
			get;
			set;
		}

		public virtual ClientService ClientService
		{
			get;
			set;
		}

		public virtual void listen()
		{
			throw new System.NotImplementedException();
		}

	}
}

