//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Listener
{
	using Definitions;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Session
	{
		public virtual Client connectedClient
		{
			get;
			set;
		}

		public virtual InputHandler InputHandler
		{
			get;
			set;
		}

		public virtual OutputHandler OutputHandler
		{
			get;
			set;
		}

		public virtual void start()
		{
			throw new System.NotImplementedException();
		}

	}
}

