//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.Parser
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Definitions;

    public class CommandParser : ICommandParser
	{
		public virtual ICommand parseCommand(string command)
		{
			throw new System.NotImplementedException();
		}

	}
}

