//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.Parser
{
    using Definitions;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class InputParser : IInputParser
	{
		public virtual string[] parse(string input)
		{
			throw new System.NotImplementedException();
		}

	}
}

