//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.ConsoleLogger
{
    using Definitions;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class ConsoleLogger : ILogger
    {
		public virtual void log(string message)
		{
            Console.WriteLine("[" + DateTime.Now.ToShortTimeString() + "] " + message);
		}

	}
}

