//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.Command
{
    using Definitions;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class Command : ICommand
    {
		public virtual string name
		{
			get;
			set;
		}

		public virtual string[] arguments
		{
			get;
			set;
		}

	}
}

