//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.CommandTarget
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Definitions;
    using System.Diagnostics;
    public class PowerDVD : ICommandTarget
	{
        private VMessages messages;
        
        [StatusRegistration("Open")]
        public string isOpen()
        {
            messages = new VMessages("CyberLink PowerDVD 12.0", "PowerDVD");
            return messages.windowExists() ? "1" : "0";
        }

        [StatusRegistration("Vol")]
        public int getCurrentVolume()
        {
            return (int)(AudioController.getMasterVolume() * 100);
        }

        [StatusRegistration("Mute")]
        public string isMuted()
        {
            return AudioController.getMute() ? "1" : "0";
        }

        [CommandRegistration("Open")]
        public void open()
        {
            Process.Start("C:\\Program Files (x86)\\CyberLink\\PowerDVD12\\PDVDLaunchPolicy.exe");
        }

        [CommandRegistration("PlayPause")]
        public void playPause()
        {
            messages.sendKey(System.Windows.Forms.Keys.Space);
        }

        [CommandRegistration("Vol")]
        public void setVol(int newVolume)
        {
            AudioController.setMasterVolume(newVolume / 100.0f);
        }

        [CommandRegistration("SwitchMute")]
        public void switchMute()
        {
            AudioController.switchMute();
        }

        [CommandRegistration("Left")]
        public void left()
        {
            messages.sendKey(System.Windows.Forms.Keys.Left);
        }

        [CommandRegistration("Up")]
        public void up()
        {
            messages.sendKey(System.Windows.Forms.Keys.Up);
        }

        [CommandRegistration("Down")]
        public void down()
        {
            messages.sendKey(System.Windows.Forms.Keys.Down);
        }

        [CommandRegistration("Right")]
        public void right()
        {
            messages.sendKey(System.Windows.Forms.Keys.Right);
        }

        [CommandRegistration("OK")]
        public void ok()
        {
            messages.sendKey(System.Windows.Forms.Keys.Enter);
        }

        [CommandRegistration("Menu")]
        public void menu()
        {
            messages.sendKey(System.Windows.Forms.Keys.L);
        }

        [CommandRegistration("Next")]
        public void next()
        {
            messages.sendKey(System.Windows.Forms.Keys.N);
        }

        [CommandRegistration("Prev")]
        public void prev()
        {
            messages.sendKey(System.Windows.Forms.Keys.P);
        }

        public string getTargetPrefix()
        {
            return "PDVD";
        }
    }
}

