//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.CommandTarget
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Definitions;
    using System.Diagnostics;
    public class PowerDVD : ICommandTarget
	{
        private const string PLAY_COMMAND = "PDVD_PLAY";
        private VMessages messages;
        protected IOutputHandler outputHandler;

        public PowerDVD(IOutputHandler outputHandler_)
        {
            outputHandler = outputHandler_;
        }

        public void refreshClientStates(Client client)
        {
            messages = new VMessages("CyberLink PowerDVD 12.0", "PowerDVD");
            string pdvdOpen = messages.windowExists() ? "1" : "0";
            if (pdvdOpen != client.getState("PDVD_Open"))
            {
                client.setState("PDVD_Open", pdvdOpen);
                outputHandler.addOutputCommand(new Command("PDVD_Open", new string[] { pdvdOpen }));
            }

            string pdvdVol = ((int)(AudioController.getMasterVolume() * 100)).ToString();
            if (pdvdVol != client.getState("PDVD_Vol"))
            {
                client.setState("PDVD_Vol", pdvdVol);
                outputHandler.addOutputCommand(new Command("PDVD_Vol", new string[] { pdvdVol }));
            }

            string pdvdMute = AudioController.getMute() ? "1" : "0";
            if (pdvdMute != client.getState("PDVD_Mute"))
            {
                client.setState("PDVD_Mute", pdvdMute);
                outputHandler.addOutputCommand(new Command("PDVD_Mute", new string[] { pdvdMute }));
            }
        }


        [CommandRegistration("PDVD_Open")]
        public void open()
        {
            Process.Start("C:\\Program Files (x86)\\CyberLink\\PowerDVD12\\PDVDLaunchPolicy.exe");
        }

        [CommandRegistration("PDVD_PlayPause")]
        public void playPause()
        {
            messages.sendKey(System.Windows.Forms.Keys.Space);
        }

        [CommandRegistration("PDVD_Vol")]
        public void setVol(int newVolume)
        {
            AudioController.setMasterVolume(newVolume / 100.0f);
        }

        [CommandRegistration("PDVD_SwitchMute")]
        public void switchMute()
        {
            AudioController.switchMute();
        }

        [CommandRegistration("PDVD_Left")]
        public void left()
        {
            messages.sendKey(System.Windows.Forms.Keys.Left);
        }

        [CommandRegistration("PDVD_Up")]
        public void up()
        {
            messages.sendKey(System.Windows.Forms.Keys.Up);
        }

        [CommandRegistration("PDVD_Down")]
        public void down()
        {
            messages.sendKey(System.Windows.Forms.Keys.Down);
        }

        [CommandRegistration("PDVD_Right")]
        public void right()
        {
            messages.sendKey(System.Windows.Forms.Keys.Right);
        }

        [CommandRegistration("PDVD_OK")]
        public void ok()
        {
            messages.sendKey(System.Windows.Forms.Keys.Enter);
        }

        [CommandRegistration("PDVD_Menu")]
        public void menu()
        {
            messages.sendKey(System.Windows.Forms.Keys.L);
        }

        [CommandRegistration("PDVD_Next")]
        public void next()
        {
            messages.sendKey(System.Windows.Forms.Keys.N);
        }

        [CommandRegistration("PDVD_Next")]
        public void prev()
        {
            messages.sendKey(System.Windows.Forms.Keys.P);
        }
       

    }
}

