//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Listener
{
    using Definitions;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Sockets;
    using System.Text;

    public class Session
	{
		public virtual Client connectedClient
		{
			get;
			set;
		}

		public virtual InputHandler InputHandler
		{
			get;
			set;
		}

		public virtual OutputHandler OutputHandler
		{
			get;
			set;
		}

        private TcpClient client;
        private NetworkStream stream;

        public Session(TcpClient client_)
        {
            client = client_;
        }

		public virtual void start()
		{
            initializeStream();
            communicate();
            client.Close();
        }

        private void initializeStream()
        {
            stream = client.GetStream();
        }

        private void communicate()
        {
            while(true)
            {
                String received = recieveAllData();
                sendData(";");
            }
        }

        private String recieveAllData()
        {
            Byte[] bytes = new Byte[256];
            String recievedData = "";
            do
            {
                int recievedBytesCount = stream.Read(bytes, 0, bytes.Length);
                recievedData += System.Text.Encoding.ASCII.GetString(bytes, 0, recievedBytesCount);
            }
            while (stream.DataAvailable);
            return recievedData;
        }

        private void sendData(String dataToSend)
        {
            byte[] msg = System.Text.Encoding.ASCII.GetBytes(dataToSend);
            stream.Write(msg, 0, msg.Length);
        }






	}
}

