//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.Definitions
{
    using Definitions;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class Client 
	{
		public virtual string name
		{
			get;
			set;
		}

		public virtual string ip
		{
			get;
			set;
		}

		public virtual Boolean allowed
		{
			get;
			set;
		}

        private Dictionary<string, string> states;

        public Client()
        {
            states = new Dictionary<string, string>();
        }


        public void setState(string key, string name)
        {
            states[key] = name;
        }

        public string getState(string key)
        {
            if (states.ContainsKey(key))
                return states[key];
            else
                return "";
        }

	}
}

