//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Definitions
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Definitions;

    public interface CommandExecuter 
	{
		Boolean tryToExecuteCommand(Command command);

	}
}

