//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.Definitions
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class Command
    {
        private string name;
        private string appName;
        private string[] arguments;

        public Command()
        {
            appName = "";
            name = "";
            arguments = new string[0];
        }

        public Command(string appName_, string name_)
        {
            appName = appName_;
            name = name_;
            arguments = new string[0];
        }

        public Command(string appName_, string name_, string[] arguments_)
        {
            appName = appName_;
            name = name_;
            arguments = arguments_;
        }

        public string getName()
        {
            return name;
        }
        public string getAppName()
        {
            return appName;
        }

        public string[] getArguments()
        {
            return arguments;
        }

        public bool hasArguments()
        {
            return arguments.Length != 0;
        }

        public override string ToString()
        {
            return appName + "_" + name + "(" + string.Join(".", arguments)  + ")";
        }

    }
}

