//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.InputHandler
{
	using Definitions;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InputHandler : IInputHandler
	{
		public virtual ICommandParser commandParser
		{
			get;
			set;
		}

		public virtual IInputParser inputParser
		{
			get;
			set;
		}

		public virtual ICommandExecuter commandExecuter
		{
			get;
			set;
		}

        public InputHandler(ICommandParser commandParser_, IInputParser inputParser_)
        {
            commandParser = commandParser_;
            inputParser = inputParser_;
        }

		public virtual void handleInput(string input)
		{
            List<string> commandStrings = inputParser.parse(input);
            foreach (String commandString in commandStrings)
            {
                ICommand command = commandParser.parseCommand(commandString);
                commandExecuter.tryToExecuteCommand(command);
            }
        }

	}
}

