//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.InputHandler
{
	using Definitions;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InputHandler : IInputHandler
	{
		public virtual ICommandParser commandParser
		{
			get;
			set;
		}

		public virtual IInputParser inputParser
		{
			get;
			set;
		}

		public virtual ICommandExecuter[] commandExecuters
		{
			get;
			set;
		}

        public InputHandler(ICommandParser commandParser_, IInputParser inputParser_, ICommandExecuter[] commandExecuters_)
        {
            commandParser = commandParser_;
            inputParser = inputParser_;
            commandExecuters = commandExecuters_;
        }

        public virtual void handleInput(string input, Client client)
        {
            List<string> commandStrings = inputParser.parse(input);
            foreach (String commandString in commandStrings)
            {
                handleCommandString(commandString);
            }
            foreach (ICommandExecuter commandExecuter in commandExecuters)
            {
                commandExecuter.refreshClientStates(client);
            }
        }

        private void handleCommandString(String commandString)
        {
            handleCommand(commandParser.parseCommand(commandString));
        }

        private void handleCommand(Command command)
        {
            foreach (ICommandExecuter commandExecuter in commandExecuters)
            {
                bool successful = commandExecuter.tryToExecuteCommand(command);
                if (successful)
                    break;
            }
        }

    }
}

