//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace InputHandler
{
	using Definitions;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InputHandler
	{
		public virtual CommandParser CommandParser
		{
			get;
			set;
		}

		public virtual InputParser InputParser
		{
			get;
			set;
		}

		public virtual CommandExecuter CommandExecuter
		{
			get;
			set;
		}

		public virtual void handleInput(string input)
		{
			throw new System.NotImplementedException();
		}

	}
}

