//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.Composer
{
    using Definitions;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class OutputComposer : IOutputComposer
    {
        private string output;
		public virtual string compose(List<string> commandStrings)
		{
            output = "";
            addCommandStrings(commandStrings);
            addOutputEnd();
            return output;
        }
        
        private void addCommandStrings(List<string> commandStrings)
        {
            foreach (string commandString in commandStrings)
            {
                addCommandString(commandString);
                addCommandSeperator();
            }
        }

        private void addCommandString(string commandString)
        {
            if (commandString.Contains(";"))
                throw new ArgumentException("The commandString must not contain a ';'! (" + commandString + ")");
            output += commandString;
        }

        private void addCommandSeperator()
        {
            output += ",";
        }

        private void addOutputEnd()
        {
            output += ";";
        }

    }
}

