//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.CommandExecuter
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Definitions;
    using System.Diagnostics;
    public class PDVDCommandExecuter : AbstractCommandExecuter
	{
        private const string PLAY_COMMAND = "PDVD_PLAY";
        private VMessages messages;

        public PDVDCommandExecuter(IOutputHandler outputHandler_)
            : base(outputHandler_)
        {
            messages = new VMessages("PowerDVD");
        }

        public override void refreshClientStates(Client client)
        {
            string pdvdOpen = messages.windowExists() ? "1" : "0";
            if (pdvdOpen != client.getState("PDVD_Open"))
            {
                client.setState("PDVD_Open", pdvdOpen);
                outputHandler.addOutputCommand(new Command("PDVD_Open", new string[] { pdvdOpen }));
            }
        }

        public override Boolean tryToExecuteCommand(Command command)
        {
            if (command.getName() == "PDVD_Open")
            {
                Process.Start("C:\\Program Files (x86)\\CyberLink\\PowerDVD12\\PDVDLaunchPolicy.exe");
                outputHandler.addOutputCommand(new Command("PDVD_Open", new string[] { "1" }));
                outputHandler.addOutputCommand(new Command("PDVD_Vol", new string[] { "60" }));
            }
            else if (command.getName() == "PDVD_PLAY")
            {
                VMessages messages = new VMessages("PowerDVD");
                messages.sendKey(System.Windows.Forms.Keys.Space);
                return true;
            }

            return false;
        }

    }
}

