//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.CommandExecuter
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Definitions;
    using System.Diagnostics;
    public class PDVDCommandExecuter : AbstractCommandExecuter
	{
        private const string PLAY_COMMAND = "PDVD_PLAY";
        private VMessages messages;

        public PDVDCommandExecuter(IOutputHandler outputHandler_)
            : base(outputHandler_)
        {
            
        }

        public override void refreshClientStates(Client client)
        {
            messages = new VMessages("CyberLink PowerDVD 12.0", "PowerDVD");
            string pdvdOpen = messages.windowExists() ? "1" : "0";
            if (pdvdOpen != client.getState("PDVD_Open"))
            {
                client.setState("PDVD_Open", pdvdOpen);
                outputHandler.addOutputCommand(new Command("PDVD_Open", new string[] { pdvdOpen }));
            }

            string pdvdVol = ((int)(AudioController.getMasterVolume() * 100)).ToString();
            if (pdvdVol != client.getState("PDVD_Vol"))
            {
                client.setState("PDVD_Vol", pdvdVol);
                outputHandler.addOutputCommand(new Command("PDVD_Vol", new string[] { pdvdVol }));
            }

            string pdvdMute = AudioController.getMute() ? "1" : "0";
            if (pdvdMute != client.getState("PDVD_Mute"))
            {
                client.setState("PDVD_Mute", pdvdMute);
                outputHandler.addOutputCommand(new Command("PDVD_Mute", new string[] { pdvdMute }));
            }
        }

        public override Boolean tryToExecuteCommand(Command command)
        {
            if (command.getName() == "PDVD_Open")
            {
                Process.Start("C:\\Program Files (x86)\\CyberLink\\PowerDVD12\\PDVDLaunchPolicy.exe");
            }
            else if (command.getName() == "PDVD_PlayPause")
            {
                messages.sendKey(System.Windows.Forms.Keys.Space);
                return true;
            }
            else if (command.getName() == "PDVD_Vol")
            {
                AudioController.setMasterVolume(Convert.ToInt32(command.getArguments()[0]) / 100.0f);
                return true;
            }
            else if (command.getName() == "PDVD_Vol")
            {
                AudioController.setMasterVolume(Convert.ToInt32(command.getArguments()[0]) / 100.0f);
                return true;
            }
            else if (command.getName() == "PDVD_SwitchMute")
            {
                AudioController.switchMute();
                return true;
            }
            else if (command.getName() == "PDVD_Left")
            {
                messages.sendKey(System.Windows.Forms.Keys.Left);
                return true;
            }
            else if (command.getName() == "PDVD_Up")
            {
                messages.sendKey(System.Windows.Forms.Keys.Up);
                return true;
            }
            else if (command.getName() == "PDVD_Down")
            {
                messages.sendKey(System.Windows.Forms.Keys.Down);
                return true;
            }
            else if (command.getName() == "PDVD_Right")
            {
                messages.sendKey(System.Windows.Forms.Keys.Right);
                return true;
            }
            else if (command.getName() == "PDVD_OK")
            {
                messages.sendKey(System.Windows.Forms.Keys.Enter);
                return true;
            }
            else if (command.getName() == "PDVD_Menu")
            {
                messages.sendKey(System.Windows.Forms.Keys.L);
                return true;
            }
            else if (command.getName() == "PDVD_Next")
            {
                messages.sendKey(System.Windows.Forms.Keys.N);
                return true;
            }
            else if (command.getName() == "PDVD_Prev")
            {
                messages.sendKey(System.Windows.Forms.Keys.P);
                return true;
            }
            return false;
        }

    }
}

