//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.CommandExecuter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Definitions;

	public class PDVDCommandExecuter : AbstractCommandExecuter
	{
        private const string PLAY_COMMAND = "PDVD_PLAY";


        public override Boolean tryToExecuteCommand(Command command)
        {
            if (command.getName() == "PDVD_PLAY")
            {
                VMessages messages = new VMessages("PowerDVD");
                messages.sendKey(System.Windows.Forms.Keys.Space);
                return true;
            }

            return false;
        }
    }
}

