//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RemoteControlServer.CommandExecuter
{   
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Definitions;

    public class WindowsCommandExecuter : AbstractCommandExecuter
    {

        public WindowsCommandExecuter(IOutputHandler outputHandler_)
            : base(outputHandler_)
        {

        }

        public override void refreshClientStates(Client client)
        {
            throw new NotImplementedException();
        }

        public override bool tryToExecuteCommand(Command command)
        {
            throw new NotImplementedException();
        }
    }
}

